# Makefile.Host
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) dbd files
# <name>.dbd will be created from <name>Include.dbd
#DBD += example.dbd

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#DB += softMotorexample.db

DB += arrayTest.db
DB += editSseq.db
DB += FuncGen.db
DB += interp.db
DB += interpNew.db
DB += sseqRecord.db
DB += transforms10.db
DB += userArrayCalcs10.db
DB += userArrayCalcs10more.db
DB += userAve10.db
DB += userAve10more.db
DB += userCalcGlobalEnable.db
DB += userCalcN.db
DB += userCalcN_noDisable.db
DB += userCalcOuts10.db
DB += userCalcOuts10more.db
DB += userCalcs10.db
DB += userCalcs10more.db
DB += userStringCalcs10.db
DB += userStringCalcs10more.db
DB += userStringSeqs10.db
DB += userStringSeqs10more.db
DB += userTransform.db
DB += userTransforms10.db
DB += userTransforms10more.db
DB += userTransforms20.db
DB += waitRecN.db
DB += yySseq.db

REQ += acalcoutArrays_settings.req
REQ += acalcout_settings.req
REQ += calcout_settings.req
REQ += editSseq_settings.req
REQ += FuncGen_settings.req
REQ += interpNew_settings.req
REQ += interp_settings.req
REQ += scalcout_settings.req
REQ += sseqRecord_settings.req
REQ += sseq_settings.req
REQ += swait_settings.req
REQ += transforms10_settings.req
REQ += transform_settings.req
REQ += userArrayCalcs10more_settings.req
REQ += userArrayCalcs10_settings.req
REQ += userAve10more_settings.req
REQ += userAve10_settings.req
REQ += userAve_settings.req
REQ += userCalcGlobalEnable_settings.req
REQ += userCalcN_noDisable_settings.req
REQ += userCalcN_settings.req
REQ += userCalcOuts10more_settings.req
REQ += userCalcOuts10_settings.req
REQ += userCalcs10more_settings.req
REQ += userCalcs10_settings.req
REQ += userStringCalcs10more_settings.req
REQ += userStringCalcs10_settings.req
REQ += userStringSeqs10more_settings.req
REQ += userStringSeqs10_settings.req
REQ += userTransforms10more_settings.req
REQ += userTransforms10_settings.req
REQ += userTransforms20_settings.req
REQ += yySseq_settings.req


#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += dbExample2.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
